services:
  - type: web
    name: quake-pro-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash startup.sh
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: USGS_FEED
        value: https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/1.0_month.geojson
